spring.application.name=sb-ecom
server.port=${PORT:8080}
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test-db


spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=password

#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_rYbTFG9om6JZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true / create-drop / update

#spring.jpa.hibernate.ddl-auto=update
